let tasks = [
      "praha 5 barrandov",
      "hlubočepy",
      "prase chrochtá",
      "vítr fouká",
      "hrom",
      "blesk",
      "odbočka",
      "nemocnice",
      "bledule",
      "vitamínový nápoj",
      "brada",
      "bludiště",
      "brod",
      "skříň",
      "stůl",
      "židle",
      "dveře",
      "čáp",
      "kůň",
      "hřib",
      "hrušeň",
      "řeka",
      "nůžky",
      "křída",
      "kříž",
      "drobeček",
      "duhové barvy",
      "chobotnice",
      "šachy",
      "bochník chleba",
      "chýše",
      "tříska",
      "střep",
      "skleněné střepy",
      "sněhové vločky",
      "chrám",
      "třešeň",
      "švestka",
      "devět úlů",
      "tři včely",
      "fagot",
      "fazole",
      "hrách",
      "dlouhé bidlo",
      "sladká kobliha",
      "černý datel",
      "rychlá raketa",
      "buldozer",
      "lední medvěd",
      "ping pong",
      "výr velký",
      "rys ostrovid",
      "dobrý oběd",
      "chodec",
      "chocholouš",
      "procházka",
      "letadlo",
      "dvě morčata",
      "bouřka",
      "divoký bizon",
      "dravá ryba",
      "lego",
      "bagr",
      "bodlák",
      "ježek",
      "bublifuk",
      "střelec",
      "pěšec",
      "gorila",
      "jupiter",
      "noční můra",
      "modré ponožky",
      "starý dub",
      "kedluben",
      "brambora",
      "mobilní telefon",
      "vodní mlýn",
      "bílý dům",
      "gepard",
      "tygr",
      "jinovatka",
      "velikonoce",
      "duben",
      "martin",
      "sladké fíky",
      "fotbalový míč",
      "zobcová flétna",
      "harfa",
      "výfuk",
      "drahý kámen",
      "mnoho minut",
      "tmavá noc",
      "zelený meloun",
      "zimní boty",
      "hluboká studna",
      "malý dron",
    ];